apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synthetic-monitor
resources:
  - base/namespace.yaml
  - base/configmap.yaml
  - base/deployment.yaml
  - base/secret.yaml
images:
  - name: synthetic-monitor
    newTag: beta
    newName: devopsplaybookio/synthetic-monitor
